// FeatureEngine
//
// Drives the feature pipeline:
//   1. Receives every market event (L2, trade, liquidation, ...) in time order.
//   2. Maintains rolling trade windows per cfg.tradeWindowsSec.
//   3. On each feature tick (every cfg.featureIntervalSec, generated by
//      backtestDay) it captures the book state, computes derived features
//      and emits a FeatureRow.
//
// All thresholds come from `StrategyConfig` — no magic numbers in the code.

import type { OrderBook } from "../replay/orderBook.js";
import { captureBookState } from "../replay/snapshotBuilder.js";
import type {
  FeatureRow,
  StrategyConfig,
  TradeAgg,
  TradeAggWindow,
} from "../strategy/types.js";
import { computeImbalance } from "./orderflowImbalance.js";
import { computeAbsorption } from "./absorption.js";
import { computeVoid } from "./liquidityVoid.js";
import { LiquidityEventTracker } from "./liquidityEvents.js";
import { VolatilityTracker } from "./volatilityRegime.js";
import type { TradeEvent, LiquidationEvent, BookL2Event } from "../data/schema.js";

interface TradeRing {
  ts: number;
  side: "buy" | "sell";
  price: number;
  amount: number;
}

export class FeatureEngine {
  private trades: TradeRing[] = [];
  private liqs: { ts: number; side: "buy" | "sell"; amount: number }[] = [];
  private readonly maxWindowMs: number;
  private readonly liqEvents = new LiquidityEventTracker(60);
  private readonly vol = new VolatilityTracker();
  // For "priceProgress": we track price at start of each tradeWindow.
  private windowStartMid = new Map<number, number>(); // windowSec -> mid at window start
  private windowStartTs = new Map<number, number>();

  constructor(private readonly cfg: StrategyConfig, private readonly book: OrderBook) {
    this.maxWindowMs = Math.max(...cfg.tradeWindowsSec) * 1000;
  }

  onTrade(ev: TradeEvent): void {
    this.trades.push({ ts: ev.ts, side: ev.side, price: ev.price, amount: ev.amount });
    this.evict(ev.ts);
  }

  onL2(ev: BookL2Event): void {
    this.liqEvents.recordL2(ev.ts, ev.side, ev.price, ev.amount, ev.isSnapshot);
  }

  onLiquidation(ev: LiquidationEvent): void {
    this.liqs.push({ ts: ev.ts, side: ev.side, amount: ev.amount });
    const cutoff = ev.ts - this.maxWindowMs;
    let i = 0;
    while (i < this.liqs.length && this.liqs[i].ts < cutoff) i++;
    if (i > 0) this.liqs = this.liqs.slice(i);
  }

  private evict(ts: number): void {
    const cutoff = ts - this.maxWindowMs;
    // Only re-slice when the head accumulates a meaningful amount, to amortise
    // the O(N) copy. Trades arrive in time-sorted order; binary search finds
    // the first entry to keep.
    if (this.trades.length === 0 || this.trades[0].ts >= cutoff) return;
    if (this.trades.length < 2048 && this.trades[0].ts >= cutoff - 60_000) return;
    let lo = 0;
    let hi = this.trades.length;
    while (lo < hi) {
      const mid = (lo + hi) >>> 1;
      if (this.trades[mid].ts < cutoff) lo = mid + 1;
      else hi = mid;
    }
    if (lo > 0) this.trades = this.trades.slice(lo);
  }

  /** Aggregate trades inside [ts - windowMs, ts]. Uses binary search for the
   * lower-bound cutoff, then forward-iterates (trades are time-sorted). For
   * each feature tick we still scan the window once per requested window
   * length, but we never look at trades older than the longest window. */
  private aggregateWindow(ts: number, windowSec: number): TradeAggWindow {
    const cutoff = ts - windowSec * 1000;
    // Binary search for the first index whose ts >= cutoff.
    let lo = 0;
    let hi = this.trades.length;
    while (lo < hi) {
      const mid = (lo + hi) >>> 1;
      if (this.trades[mid].ts < cutoff) lo = mid + 1;
      else hi = mid;
    }
    let buy = 0,
      sell = 0,
      n = 0;
    let pv = 0,
      v = 0;
    let pHi = -Infinity,
      pLo = +Infinity;
    for (let i = lo; i < this.trades.length; i++) {
      const t = this.trades[i];
      if (t.ts > ts) break;
      if (t.side === "buy") buy += t.amount;
      else sell += t.amount;
      pv += t.price * t.amount;
      v += t.amount;
      n++;
      if (t.price > pHi) pHi = t.price;
      if (t.price < pLo) pLo = t.price;
    }
    return {
      windowSec,
      buyVolume: buy,
      sellVolume: sell,
      delta: buy - sell,
      trades: n,
      vwap: v > 0 ? pv / v : null,
      highPrice: Number.isFinite(pHi) ? pHi : null,
      lowPrice: Number.isFinite(pLo) ? pLo : null,
    };
  }

  /** Build a complete FeatureRow at time ts using the *current* book. */
  buildFeatureRow(ts: number, qualityFlags: string[]): FeatureRow {
    const bookState = captureBookState(this.book, ts, this.cfg, qualityFlags);
    this.vol.push(ts, bookState.mid);

    const windows: { [secKey: string]: TradeAggWindow } = {};
    for (const w of this.cfg.tradeWindowsSec) {
      windows[w.toString()] = this.aggregateWindow(ts, w);
    }
    const tradeAgg: TradeAgg = { ts, windows };

    const imbalance = computeImbalance(bookState);

    // Pressure & absorption keyed off the longest trade window.
    const refWin = this.cfg.tradeWindowsSec[this.cfg.tradeWindowsSec.length - 1];
    const refKey = refWin.toString();
    const w = windows[refKey];
    const totalVol = w.buyVolume + w.sellVolume;
    const buyPressure = totalVol > 0 ? w.buyVolume / totalVol : 0;
    const sellPressure = totalVol > 0 ? w.sellVolume / totalVol : 0;
    const aggressiveFlowRatio = totalVol > 0 ? Math.max(buyPressure, sellPressure) : 0;

    // Price progress: compare current mid to mid at start of window. Use
    // binary search so we don't scan the full ring on every feature tick.
    const startTs = ts - refWin * 1000;
    let startMid: number | null = bookState.mid ?? null;
    {
      let lo = 0;
      let hi = this.trades.length;
      while (lo < hi) {
        const m = (lo + hi) >>> 1;
        if (this.trades[m].ts < startTs) lo = m + 1;
        else hi = m;
      }
      if (lo < this.trades.length) startMid = this.trades[lo].price;
    }
    const curMid = bookState.mid ?? (this.trades.length > 0 ? this.trades[this.trades.length - 1].price : null);
    let progressUpPct = 0,
      progressDownPct = 0;
    if (startMid !== null && curMid !== null && startMid > 0) {
      const delta = (curMid - startMid) / startMid;
      if (delta > 0) progressUpPct = delta * 100;
      else progressDownPct = -delta * 100;
    }

    const absorption = computeAbsorption({
      sellVolumeWindow: w.sellVolume,
      buyVolumeWindow: w.buyVolume,
      priceProgressUpPct: progressUpPct,
      priceProgressDownPct: progressDownPct,
      totalTradeVolumeWindow: totalVol,
    });

    const voidRes = computeVoid(bookState);

    const liqSnap = this.liqEvents.snapshot(ts);
    const liquidityEvents = {
      bidAddRate: liqSnap.bidAddVol / Math.max(1, liqSnap.windowSec),
      bidRemoveRate: (liqSnap.bidRemoveVol + liqSnap.bidCancelVol) / Math.max(1, liqSnap.windowSec),
      askAddRate: liqSnap.askAddVol / Math.max(1, liqSnap.windowSec),
      askRemoveRate: (liqSnap.askRemoveVol + liqSnap.askCancelVol) / Math.max(1, liqSnap.windowSec),
      bidRefillScore: this.liqEvents.bidRefillScore(liqSnap),
      askRefillScore: this.liqEvents.askRefillScore(liqSnap),
      bidThinningScore: this.liqEvents.bidThinningScore(liqSnap),
      askThinningScore: this.liqEvents.askThinningScore(liqSnap),
    };

    const realizedVolPct = this.vol.realizedVolPct();
    const range1mPct = this.vol.range1mPct(ts);
    const rangeCompression = this.vol.isRangeCompressed(ts, this.cfg.zone.candidate.rangeCompressionPct);

    let liqBuyVol = 0;
    let liqSellVol = 0;
    {
      const cutoff = ts - 60_000;
      for (let i = this.liqs.length - 1; i >= 0; i--) {
        const l = this.liqs[i];
        if (l.ts < cutoff) break;
        if (l.side === "buy") liqBuyVol += l.amount;
        else liqSellVol += l.amount;
      }
    }

    return {
      ts,
      book: bookState,
      trades: tradeAgg,
      imbalance,
      pressure: { buyPressure, sellPressure, aggressiveFlowRatio },
      absorption: {
        ...absorption,
        priceProgressDownPct: progressDownPct,
        priceProgressUpPct: progressUpPct,
      },
      liquidityVoid: voidRes,
      liquidityEvents,
      volatility: { realizedVolPct, range1mPct },
      rangeCompression,
      forcedFlow: { liqBuyVol, liqSellVol },
      qualityFlags: bookState.qualityFlags.slice(),
    };
  }
}
